ServerRoot "{{APACHE_ROOT}}"
Listen 80

LoadModule php_module "{{PHP_APACHE_DLL}}"
PHPINIDir "{{PHP_ROOT}}"

ServerName localhost:80
DocumentRoot "{{WWW_ROOT}}"
DirectoryIndex index.php index.html

<Directory "{{WWW_ROOT}}">
    Options Indexes FollowSymLinks Includes ExecCGI
    AllowOverride All
    Require all granted
</Directory>

ErrorLog "{{APACHE_LOGS}}/error.log"
CustomLog "{{APACHE_LOGS}}/access.log" common
TypesConfig conf/mime.types
AddType application/x-httpd-php .php
